local M = {}

function M.setup(palette)
	local c = palette.colors
	local hi = vim.api.nvim_set_hl

	hi(0, "Normal",          { fg = c.fg,        bg = c.bg })
	hi(0, "NormalFloat",     { fg = c.fg,        bg = c.bg1 })
	hi(0, "FloatBorder",     { fg = c.border,    bg = c.bg1 })
	hi(0, "CursorLine",      { bg = c.bg2 })
	hi(0, "CursorLineNr",    { fg = c.yellow,    bold = true })
	hi(0, "LineNr",          { fg = c.comment })
	hi(0, "SignColumn",      { fg = c.comment,   bg = c.bg })
	hi(0, "ColorColumn",     { bg = c.bg2 })
	hi(0, "Visual",          { bg = c.selection })
	hi(0, "VisualNOS",       { bg = c.selection })
	hi(0, "Search",          { fg = c.bg,        bg = c.yellow })
	hi(0, "IncSearch",       { fg = c.bg,        bg = c.orange })
	hi(0, "MatchParen",      { fg = c.orange,    bold = true })
	hi(0, "StatusLine",      { fg = c.fg,        bg = c.bg1 })
	hi(0, "StatusLineNC",    { fg = c.comment,   bg = c.bg1 })
	hi(0, "VertSplit",       { fg = c.border })
	hi(0, "WinSeparator",    { fg = c.border })
	hi(0, "Pmenu",           { fg = c.fg,        bg = c.bg1 })
	hi(0, "PmenuSel",        { fg = c.bg,        bg = c.blue })
	hi(0, "PmenuSbar",       { bg = c.bg2 })
	hi(0, "PmenuThumb",      { bg = c.border })
	hi(0, "Folded",          { fg = c.comment,   bg = c.bg2 })
	hi(0, "FoldColumn",      { fg = c.comment,   bg = c.bg })
	hi(0, "EndOfBuffer",     { fg = c.bg })
	hi(0, "NonText",         { fg = c.comment })
	hi(0, "SpecialKey",      { fg = c.comment })
	hi(0, "Whitespace",      { fg = c.bg2 })


	-- Syntax
	hi(0, "Comment",         { fg = c.comment,   italic = true })
	hi(0, "String",          { fg = c.green })
	hi(0, "Character",       { fg = c.green })
	hi(0, "Number",          { fg = c.purple })
	hi(0, "Float",           { fg = c.purple })
	hi(0, "Boolean",         { fg = c.orange })
	hi(0, "Constant",        { fg = c.purple })
	hi(0, "Identifier",      { fg = c.fg })
	hi(0, "Function",        { fg = c.blue })
	hi(0, "Keyword",         { fg = c.red,       bold = true })
	hi(0, "Conditional",     { fg = c.red })
	hi(0, "Repeat",          { fg = c.red })
	hi(0, "Operator",        { fg = c.cyan })
	hi(0, "Type",            { fg = c.yellow })
	hi(0, "StorageClass",    { fg = c.yellow })
	hi(0, "Structure",       { fg = c.yellow })
	hi(0, "PreProc",         { fg = c.pink })
	hi(0, "Include",         { fg = c.pink })
	hi(0, "Define",          { fg = c.pink })
	hi(0, "Macro",           { fg = c.pink })
	hi(0, "Special",         { fg = c.orange })
	hi(0, "SpecialChar",     { fg = c.orange })
	hi(0, "Error",           { fg = c.error })
	hi(0, "Todo",            { fg = c.bg,        bg = c.yellow, bold = true })
	hi(0, "Underlined",      { underline = true })
	hi(0, 'LineNrAbove',	{ fg=c.fg1, bold=true })
	hi(0, 'LineNr',			{ fg='white', bold=true })
	hi(0, 'CursorLineNr',	{ fg = c.blue, bold = true })
	hi(0, 'LineNrBelow',	{ fg=c.fg1, bold=true })

	-- Treesitter 
	hi(0, "@comment",              { link = "Comment" })
	hi(0, "@string",               { link = "String" })
	hi(0, "@string.escape",        { fg = c.orange })
	hi(0, "@string.special",       { fg = c.orange })
	hi(0, "@number",               { link = "Number" })
	hi(0, "@float",                { link = "Float" })
	hi(0, "@boolean",              { link = "Boolean" })
	hi(0, "@constant",             { link = "Constant" })
	hi(0, "@constant.builtin",     { fg = c.orange })
	hi(0, "@variable",             { fg = c.fg2 })
	hi(0, "@variable.builtin",     { fg = c.orange,  italic = true })
	hi(0, "@variable.parameter",   { fg = c.fg3, italic = true })
	hi(0, "@function",             { link = "Function" })
	hi(0, "@function.call",        { fg = c.blue })
	hi(0, "@function.builtin",     { fg = c.cyan })
	hi(0, "@method",               { fg = c.blue })
	hi(0, "@method.call",          { fg = c.blue })
	hi(0, "@constructor",          { fg = c.yellow })
	hi(0, "@keyword",              { link = "Keyword" })
	hi(0, "@keyword.function",     { fg = c.red,     bold = true })
	hi(0, "@keyword.return",       { fg = c.red,     bold = true })
	hi(0, "@keyword.operator",     { fg = c.cyan })
	hi(0, "@conditional",          { link = "Conditional" })
	hi(0, "@repeat",               { link = "Repeat" })
	hi(0, "@operator",             { link = "Operator" })
	hi(0, "@type",                 { link = "Type" })
	hi(0, "@type.builtin",         { fg = c.yellow,  italic = true })
	hi(0, "@field",                { fg = c.lavender })
	hi(0, "@property",             { fg = c.lavender })
	hi(0, "@namespace",            { fg = c.fg })
	hi(0, "@include",              { link = "Include" })
	hi(0, "@punctuation.bracket",  { fg = c.fg })
	hi(0, "@punctuation.delimiter",{ fg = c.fg })
	hi(0, "@tag",                  { fg = c.red })
	hi(0, "@tag.attribute",        { fg = c.yellow })
	hi(0, "@tag.delimiter",        { fg = c.fg })

	-- LSP
	hi(0, "DiagnosticError",            { fg = c.error })
	hi(0, "DiagnosticWarn",             { fg = c.warning })
	hi(0, "DiagnosticInfo",             { fg = c.info })
	hi(0, "DiagnosticHint",             { fg = c.hint })
	hi(0, "DiagnosticUnderlineError",   { undercurl = true, sp = c.error })
	hi(0, "DiagnosticUnderlineWarn",    { undercurl = true, sp = c.warning })
	hi(0, "DiagnosticUnderlineInfo",    { undercurl = true, sp = c.info })
	hi(0, "DiagnosticUnderlineHint",    { undercurl = true, sp = c.hint })
	hi(0, "LspReferenceText",           { bg = c.selection })
	hi(0, "LspReferenceRead",           { bg = c.selection })
	hi(0, "LspReferenceWrite",          { bg = c.selection, bold = true })

	-- Git (Gitsigns)
	hi(0, "GitSignsAdd",            { fg = c.git_add })
	hi(0, "GitSignsChange",         { fg = c.git_change })
	hi(0, "GitSignsDelete",         { fg = c.git_delete })

	-- nvim-tree
	hi(0, "NvimTreeNormal",         { fg = c.fg,      bg = c.bg1 })
	hi(0, "NvimTreeFolderName",     { fg = c.blue })
	hi(0, "NvimTreeOpenedFolderName",{ fg = c.blue,   bold = true })
	hi(0, "NvimTreeFolderIcon",     { fg = c.blue })
	hi(0, "NvimTreeRootFolder",     { fg = c.purple,  bold = true })
	hi(0, "NvimTreeGitDirty",       { fg = c.git_change })
	hi(0, "NvimTreeGitNew",         { fg = c.git_add })
	hi(0, "NvimTreeGitDeleted",     { fg = c.git_delete })
	hi(0, "NvimTreeIndentMarker",   { fg = c.border })
	hi(0, "NvimTreeSpecialFile",    { fg = c.yellow })

end

return M
